# Geospatial using Plotly & Mapbox

In [3]:
# import dependancies
from datetime import datetime, timedelta
import plotly.express as px
import pandas as pd
import chart_studio
import chart_studio.plotly as py

# enter username and password for plotly api
chart_studio.tools.set_credentials_file(username='#############', 
                                        api_key='################')

In [7]:
# read in the data
df = pd.read_parquet('/content/accident_data_time_series.parquet')

In [8]:
# check data
df.head()

,Accident_Index,1st_Road_Class,1st_Road_Number,2nd_Road_Class,2nd_Road_Number,Accident_Severity,Carriageway_Hazards,Date,Day_of_Week,Did_Police_Officer_Attend_Scene_of_Accident,...,Police_Force,Road_Surface_Conditions,Road_Type,Special_Conditions_at_Site,Speed_limit,Time,Urban_or_Rural_Area,Weather_Conditions,Year,InScotland
0,200501BS00001,A,3218.0,None,0.0,Serious,None,2005-01-04,Tuesday,1.0,...,Metropolitan Police,Wet or damp,Single carriageway,None,30.0,17:42,Urban,Raining no high winds,2005,No
1,200501BS00002,B,450.0,C,0.0,Slight,None,2005-01-05,Wednesday,1.0,...,Metropolitan Police,Dry,Dual carriageway,None,30.0,17:36,Urban,Fine no high winds,2005,No
2,200501BS00003,C,0.0,None,0.0,Slight,None,2005-01-06,Thursday,1.0,...,Metropolitan Police,Dry,Single carriageway,None,30.0,00:15,Urban,Fine no high winds,2005,No
3,200501BS00004,A,3220.0,None,0.0,Slight,None,2005-01-07,Friday,1.0,...,Metropolitan Police,Dry,Single carriageway,None,30.0,10:35,Urban,Fine no high winds,2005,No
4,200501BS00005,Unclassified,0.0,None,0.0,Slight,None,2005-01-10,Monday,1.0,...,Metropolitan Police,Wet or damp,Single carriageway,None,30.0,21:13,Urban,Fine no high winds,2005,No

In [9]:
# filter df dropping slight
df = df[df.Accident_Severity != "Slight"]

In [10]:
# check it has worked
df.head()

,Accident_Index,1st_Road_Class,1st_Road_Number,2nd_Road_Class,2nd_Road_Number,Accident_Severity,Carriageway_Hazards,Date,Day_of_Week,Did_Police_Officer_Attend_Scene_of_Accident,...,Police_Force,Road_Surface_Conditions,Road_Type,Special_Conditions_at_Site,Speed_limit,Time,Urban_or_Rural_Area,Weather_Conditions,Year,InScotland
0,200501BS00001,A,3218.0,None,0.0,Serious,None,2005-01-04,Tuesday,1.0,...,Metropolitan Police,Wet or damp,Single carriageway,None,30.0,17:42,Urban,Raining no high winds,2005,No
16,200501BS00019,Unclassified,0.0,Unclassified,0.0,Serious,None,2005-01-20,Thursday,1.0,...,Metropolitan Police,Dry,Single carriageway,None,30.0,00:15,Urban,Fine no high winds,2005,No
19,200501BS00022,A,4.0,Unclassified,0.0,Serious,None,2005-01-08,Saturday,1.0,...,Metropolitan Police,Dry,Single carriageway,None,30.0,03:00,Urban,Fine no high winds,2005,No
30,200501BS70003,B,412.0,Unclassified,0.0,Serious,None,2005-02-01,Tuesday,1.0,...,Metropolitan Police,Wet or damp,One way street,None,30.0,17:30,Urban,Raining no high winds,2005,No
52,200501BS70029,B,450.0,None,0.0,Serious,None,2005-02-15,Tuesday,1.0,...,Metropolitan Police,Dry,Single carriageway,None,30.0,18:15,Urban,Fine no high winds,2005,No

In [11]:
# ensure the data is in the correct format
df['Date'] = pd.to_datetime(df['Date'],format="%Y-%m-%d")

In [12]:
# create a string to use for the plot table
df['dt_str'] = df['Date'].apply(lambda x: x.strftime("%d-%b-%Y"))

In [13]:
# sort the values by data
df.sort_values(by = ['Date'], inplace=True)

In [14]:
# sort the data for plotly reading
date1 = datetime(2005,1,1)
date2 = datetime(2017,12,31)
df = df[(df['Date'] >= date1) & (df['Date'] <= date2)]

In [15]:
# list columns to see what data points could be useful. 
df.columns

Index(['Accident_Index', '1st_Road_Class', '1st_Road_Number', '2nd_Road_Class',
       '2nd_Road_Number', 'Accident_Severity', 'Carriageway_Hazards', 'Date',
       'Day_of_Week', 'Did_Police_Officer_Attend_Scene_of_Accident',
       'Junction_Control', 'Junction_Detail', 'Latitude', 'Light_Conditions',
       'Local_Authority_(District)', 'Local_Authority_(Highway)',
       'Location_Easting_OSGR', 'Location_Northing_OSGR', 'Longitude',
       'LSOA_of_Accident_Location', 'Number_of_Casualties',
       'Number_of_Vehicles', 'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Police_Force',
       'Road_Surface_Conditions', 'Road_Type', 'Special_Conditions_at_Site',
       'Speed_limit', 'Time', 'Urban_or_Rural_Area', 'Weather_Conditions',
       'Year', 'InScotland', 'dt_str'],
      dtype='object')

In [ ]:
fig = px.scatter_mapbox(df, lat="Latitude", 
                        lon="Longitude", 
                        hover_name="Date", 
                        hover_data=["Accident_Index","Accident_Severity", 
                                    "Number_of_Casualties"],
                        color_discrete_sequence=["red"], 
                        zoom=4.5, height=750, width=700, 
                        animation_frame="dt_str", 
                        size_max=10)
fig.update_layout(
    mapbox_style="open-street-map")
# you can adjust the map view 
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0}, 
                  mapbox=dict(
                      pitch=0,
                      bearing=0
                  ))
fig.show()

In [17]:
# write to a html file
fig.write_html("map_test.html")

In [ ]:
# upload to plotly platform (this is too large for the time being)
#py.plot(fig, filename = 'omdena_liverpool_map', auto_open=True)